name: Deploy to GitHub Pages

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Clean previous build
        run: |
          rm -rf .next out
          echo "Cleaned .next and out directories"
          
      - name: Debug Next.js config
        run: |
          echo "Next.js configuration:"
          cat next.config.ts
          echo "Package.json build script:"
          grep -A 5 -B 5 '"build"' package.json
          
      - name: Build with Next.js
        run: |
          echo "Running Next.js build..."
          npm run build
          echo "Build completed"
          echo "Next.js version:"
          npx next --version
          echo "Contents of current directory:"
          ls -la
          echo "Contents of .next directory:"
          ls -la .next/ || echo "No .next directory found"
          echo "Checking if out directory was created:"
          ls -la out/ || echo "No out directory found"
        env:
          NODE_ENV: production
        
      - name: Verify output directory
        run: |
          echo "Checking build output..."
          ls -la
          if [ -d "out" ]; then
            echo "✅ out directory exists"
            ls -la out/
          else
            echo "❌ out directory missing"
            exit 1
          fi

      - name: Setup Pages (after build)
        uses: actions/configure-pages@v4
        
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: out

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4